### ISSUE TITLE
When running npm install, bcrypt gives errors

### ISSUE THREAD

**Issue by T4lith4** [Merge-Team/merge-meetups#1]
Please download and read the txt file below:
[meetup-debugging.txt](https://github.com/Merge-Team/merge-meetups/files/4097803/meetup-debugging.txt)

**Comment by jacobdcastro** [comment]
We've decided to use [md5](https://github.com/pvorb/node-md5) instead of bcrypt. Bcrypt's peer dependencies are out of date. The md5 seems more stable.
